Example how to read a shapefile and convert it to a geo-crate data-structure
tmontaigu/shapefile-rs pull request #23
Opened 2021-06-08 14:02 UTC by michelk

2021-06-12 15:15 UTC, tmontaigu requested changes

2021-06-12 15:15 UTC, tmontaigu commented on examples/read-polygon-shapefile-and-convert-to-geo-types/Cargo.toml
> +dbase = "0.2.0"
You actually don't need to add dbase as a dependency as its alreeady a shapefile dependency.
Remove it and in the main.rs add `use shapefile::dbase`

2021-06-12 15:15 UTC, tmontaigu commented on examples/read-polygon-shapefile-and-convert-to-geo-types/src/main.rs
> +                let point_id = match point_record
For both of the `id` I find something like this to be cleaner:

```Rust
let point_id = match point_record.get("id") {
    Some(dbase::FieldValue::Numeric(Some(x))) => x,
    Some(_) => panic!("Expected 'id' to be a numeric"),
    None => panic!("Field 'id' is not within point-dataset"),
};
```

2021-06-12 15:15 UTC, tmontaigu commented on examples/read-polygon-shapefile-and-convert-to-geo-types/src/main.rs
> +            } else {
That else has no purpose, you should remove it

2021-06-12 15:19 UTC, tmontaigu commented
Also, I think the name of the folder is too long, it should be shorter, like "geotype-example" or "geotype-integration" or something else but shorter.

2021-06-14 13:11 UTC, michelk commented
Thanks for the suggestions; I just applied them.

2021-06-14 20:25 UTC, merged

2021-06-14 20:26 UTC, tmontaigu commented
Thanks for the example

2021-06-15 10:41 UTC, michelk commented
Thanks. 

I have some problems to write another example: See [README](https://github.com/michelk/shapefile-rs/blob/read-example/examples/geotype-example/README.md) for a description and some [beginner code](https://github.com/michelk/shapefile-rs/blob/read-example/examples/geotype-example/src/bin/geotype-csv-example.rs).

I just have a knot in the brain, how to do the merge of csv::StringRecord and dbase::Record. Maybe you have some pointers? Thanks a lot.

2021-06-16 14:56 UTC, tmontaigu commented
StringRecord seems to be a Collection of Strings so you will need to convert the content of the FieldValue to String.

2021-06-17 07:29 UTC, michelk commented
Ok thanks. Now I have a working prototype. I added some information to the  [README](https://github.com/michelk/shapefile-rs/blob/read-example/examples/geotype-example/README.md) and the [ code](https://github.com/michelk/shapefile-rs/blob/read-example/examples/geotype-example/src/bin/geotype-csv-example.rs).

Would you consider to accept a PR with the new example?

2021-06-17 07:33 UTC, michelk commented
Additionally, I had to add the Clone trait to dbase::Record, to get the example working.

2021-06-20 09:44 UTC, tmontaigu commented
Yeah dbase::Record should derive Clone.

As for the example, i'm sure yet, I feel like this example is maybe too verbose, and stuff that is specific to the shapefile/dbase is too 'buried'.

One comment that I have about the code tho, is that the I think there is more `.clone()` that should be needed